const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),read=f=>fs.readFileSync(path.join(ROOT,f),"utf8");
test("Arena Hub R1 manifest and nine-slice contract",()=>{const m=JSON.parse(read("r2-upload/manifest.json")),c=read("src/ui/components.js"),s=read("src/data/styles.js");for(const k of ["emblem","panelFrame","rowFrame"])assert.ok(m.assets.arenaUi.hub[k]);for(const k of ["active","inactive"])assert.ok(m.assets.arenaUi.tabs[k]);for(const k of ["battle","setup","ranking","history"])assert.ok(m.assets.arenaUi.icons[k]);assert.match(c,/md-arena-brand-emblem/);assert.match(c,/md-arena-tab-icon/);assert.match(c,/className: !match \? "md-card md-arena-hub-panel md-arena-summary-panel" : "md-card"/);assert.match(s,/border-image-slice:64 fill/);assert.match(s,/border-image-slice:48 fill/);assert.match(s,/border-image-slice:22 fill/);assert.match(s,/Ver 1\\.0\\.49/);});


test("Arena Hub Extension R1 manifest and runtime contract",()=>{const m=JSON.parse(read("r2-upload/manifest.json")),c=read("src/ui/components.js"),s=read("src/data/styles.js");for(const k of ["primary","secondary","danger"])assert.ok(m.assets.arenaUi.buttons[k]);for(const k of ["bronze","silver","gold","diamond"])assert.ok(m.assets.arenaUi.tiers[k]);for(const k of ["frame","fill","rewardSlot"])assert.ok(m.assets.arenaUi.progress[k]);for(const k of ["season","refresh","playerCard","info","playMilestone","winMilestone","attackHistory","defenseHistory"])assert.ok(m.assets.arenaUi.icons[k]);assert.match(c,/ARENA_HUB_MILESTONE_PRESENTATION/);assert.match(c,/arenaUi\.tiers\.bronze/);assert.match(c,/md-arena-milestone-panel/);assert.match(c,/className: !match \? "md-card md-arena-hub-panel md-arena-summary-panel" : "md-card"/);assert.match(s,/border-image-slice:32 fill/);assert.match(s,/border-image-slice:16 fill/);assert.match(s,/\.md-arena-progress-fill \{[^}]*width:0;[^}]*background-color:#2f8dff/);assert.doesNotMatch(s,/clip-path:inset\(0 calc\(100% - var\(--arena-progress\)\)/);assert.match(s,/Ver 1\\.0\\.49/);});


test("Arena Hub Extension R1 artwork is gated to Hub mode",()=>{const c=read("src/ui/components.js");assert.match(c,/!match && currentTierBadge/);assert.match(c,/!match && arenaHubAssets\.icons\.season/);assert.match(c,/md-arena-summary-hint/);assert.doesNotMatch(c,/CURRENCY INFO/);});
